FROM httpd:2.4.68-alpine3.24@sha256:1b766f17b84026429b7cb243317b142921b24432336e798bc881c43f45ed9567

RUN set -eux; \
    sed -ri 's!^#(LoadModule proxy_module modules/mod_proxy.so)!\1!' /usr/local/apache2/conf/httpd.conf; \
    sed -ri 's!^#(LoadModule proxy_http_module modules/mod_proxy_http.so)!\1!' /usr/local/apache2/conf/httpd.conf; \
    sed -ri 's!^#(LoadModule headers_module modules/mod_headers.so)!\1!' /usr/local/apache2/conf/httpd.conf; \
    sed -ri 's!^#(LoadModule setenvif_module modules/mod_setenvif.so)!\1!' /usr/local/apache2/conf/httpd.conf; \
    sed -ri 's!^#(LoadModule unique_id_module modules/mod_unique_id.so)!\1!' /usr/local/apache2/conf/httpd.conf; \
    sed -ri 's!^Listen 80$!Listen 8080!' /usr/local/apache2/conf/httpd.conf; \
    mkdir -p /var/www/vault-empty; \
    printf '\nInclude conf/extra/vault-staging.conf\n' >> /usr/local/apache2/conf/httpd.conf

COPY deploy/docker/apache-staging.conf /usr/local/apache2/conf/extra/vault-staging.conf

EXPOSE 8080
